version: "3.7"
services:
  sql-server-db:
    restart: always
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    environment:
      SA_PASSWORD: "develop123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    user: root
    depends_on:
      - sql-server-db


  invapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appinventory
    depends_on:
      - sql-server-db
    ports:
      - "8181:3589"
